name: Example Workflow

on:
  workflow_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:

      - name: checkout files from repo
        uses: actions/checkout@v2

      - name: set up packages
        run: | 
          echo pip3 install pytest
          pip3 install pytest

      - name: run tests
        run: 
          echo pytest test_parser.py
          pytest test_parser.py
